# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('introduccion', models.CharField(max_length=140)),
                ('cuerpo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publish_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('PUB', 'Publicado'), ('NOP', 'No publicado')], default='NOP', max_length=3)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_posts', to='blogs.Blog')),
            ],
        ),
    ]
