# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_posts_category', to='blogs.Categoria'),
            preserve_default=False,
        ),
    ]
